### PR TITLE
Stubbing out support for EuroPar submissions

### PR DESCRIPTION
**Pull request by arfon**
:wave: @tarleb – we're going to be publishing a small number of papers with EuroPar as a JOSS special issue. As such, I'd like to mimic the functionality we have with AAS today.

My hope is that with these changes if authors include the following in their front matter:

```
europar-doi: 10.3847/xxxxx
```

Then this should trigger the template to render with their logo and the snippet. Does this look about right to you?

/ cc @danielskatz for visibility

### CODE REVIEW

**Comment by tarleb** [comment]
LGTM! Should we modify the new ConTeXt template as well?

**Review by tarleb — APPROVED** [review]

**Comment by arfon** [comment]
> LGTM! Should we modify the new ConTeXt template as well?

Definitely! Whereabouts is that?

**Comment by tarleb** [comment]
The `data/templates/default.context` file contains the template. The usual way to add an image is to define it with a `\startsetups ... \stopsetups` environment and then use that with `\directsetup{...}` in the place where you want it.  Search for `journalLogo` to see an example.

**Comment by arfon** [comment]
Got it. Thanks! Just to confirm though, this would only be needed for the new paper look/feel right? i.e., if we merged this as-is, we could start generating EuroPar-supported papers now with the existing PDFs?

**Comment by tarleb** [comment]
Right, that would be enough.

**Comment by arfon** [comment]
OK, going to merge here then to test this out. Will revisit the Context template later.

**Pull request merged**
