### PR TITLE
Use flat folder for JATS output

### PR DESCRIPTION
**Pull request by tarleb**

### CODE REVIEW

**Comment by tarleb** [comment]
@xuanxu I forgot, how are the artifacts copied to the target repository? Would it help if Inara took a target directory as another argument?

**Comment by xuanxu** [comment]
If I understand it correctly, we need:

- All the images in the same directory as the jats file
- The correct relative references in the JATS file to the images
- A directory to know what to upload to the final repository

Would it be easier to have jats file and images in a separate `jats_files` (for example) directory?

**Comment by arfon** [comment]
> Would it be easier to have jats file and images in a separate jats_files (for example) directory?

Yeah, I agree I think this would be the ideal solution here (a self-contained folder with everything in related to JATS, but also without any nested folders).

**Comment by arfon** [comment]
> we now create a folder paper.jats that has all the relevant data, including the images, all at the same level. Example:

Just for absolute clarity – the paper (e.g., `paper.jats.xml`) will also be in that same directory?

**Comment by xuanxu** [comment]
I've prepared a branch in the GH actions to use this changes and keep the paper.jats folder when uploading to the papers repo. I'll merge [the changes](https://github.com/xuanxu/upload-files-action/pull/1) once this new version of inara is up.

**Comment by xuanxu** [comment]
> Just for absolute clarity – the paper (e.g., `paper.jats.xml`) will also be in that same directory?

Yes, the `paper.jats` folder includes the xml and any media files

**Comment by tarleb** [comment]
Sorry, I'm not entirely clear on these questions:

1. Is there more work needed on Inara?
2. Who will merge the PRs? (I assume @xuanxu?)

**Comment by xuanxu** [comment]
>     1. Is there more work needed on Inara?

I don't think so (every new commit is automatically re-publishing the Inara Docker image, right?). This is ready.
 
>     2. Who will merge the PRs? (I assume @xuanxu?)

I'll merge them all at the same time tomorrow morning so I can monitor the actions.

**Comment by arfon** [comment]
Thanks @tarleb!

**Comment by arfon** [comment]
Hang on, isn't this URL incorrect? 

https://github.com/openjournals/joss-papers/blob/eff5cbbffd13961e4399e80bde0033daed1221de/joss.05618/paper.jats/10.21105.joss.05618.jats#L159

(i.e., I think it should be `./matbench-genmetrics.png`)

**Comment by xuanxu** [comment]
@arfon ouch, you are right, the files are in the right place but the URLs for images in the paper all point to `/paper.jats/` folder https://github.com/openjournals/joss-papers/blob/master/joss.06017/paper.jats/10.21105.joss.06017.jats#L253
Is this easy to fix @tarleb?

**Comment by tarleb** [comment]
Argh, my bad. I'll open a new PR in a minute.

**Comment by tarleb** [comment]
See #53. Do we want to keep the `/paper.jats/` path or shorten that to just `/jats/`?

**Comment by xuanxu** [comment]
@arfon can you reaccept this one to regenerate the files? https://github.com/openjournals/joss-reviews/issues/06017

**Comment by arfon** [comment]
Done

**Comment by xuanxu** [comment]
Hey @tarleb, merging #53 seems to have modified the DTD declaration in the generated JATS file, see the first lines here: 
https://github.com/openjournals/joss-papers/commit/554242d5c9f19c5018a074c1b8fd8d6b3142537a
Is that intentional (in which case I'll update the xml validator) or is a bug?

**Comment by xuanxu** [comment]
I've updated the XML validator gem so now we can validate both the [Journal Publishing](https://jats.nlm.nih.gov/publishing/) and the [Journal Archiving and Interchange](https://jats.nlm.nih.gov/archiving/) tag sets.

Still not sure which of them we should use in Inara to generate the paper.jats file.

**Comment by tarleb** [comment]
This was not intended, sorry. I'll push the fix without PR.

Note to self: better not to rush out patches at 2am after the ESC.

**Comment by xuanxu** [comment]
> Do we want to keep the `/paper.jats/` path or shorten that to just `/jats/`?

hey @tarleb, I noticed that sometimes there's already a `paper.jats` file in the repository created by the authors of the submission and that has caused conflicts on a [couple](https://github.com/openjournals/joss-papers/actions/runs/9068348241/job/24915463922#step:3:864) [reviews](https://github.com/openjournals/joss-papers/actions/runs/9063438071/job/24899375410#step:3:870) already, so on a second thought it's better to use another name for the folder, `/jats/` or `/paper_jats/` for instance.

**Comment by arfon** [comment]
Hey both. Can I just check where we landed here? In the joss-papers repo I see a PR that's [flattening folders](https://github.com/openjournals/joss-papers/pull/5323) (good), but doesn't seem to be putting the papers into a `jats` folder.

Also, [this most recently-merged PR](https://github.com/openjournals/joss-papers/commit/103bebc6c2967760b4dcdb607a437934e5755896) looks to still be using the old `paper.jats` repo format?

**Comment by xuanxu** [comment]
Right now, in the `joss-papers` repo all the jats files (.jats and images) are placed in a `paper.jats` folder, so the structure is something like this:
````
joss-paper-1234.pdf
\paper.jats
    joss-paper-1234.jats
    image1.png
    image2.png
```

The `paper.jats` folder name was problematic when generated in the GitHub action, where sometimes conflicted with other files present in the submitted sofwtare's repo, so now inara creates the jats output in a folder called `jats`, it is an internal change. When uploading the files to a branch in the joss-papers repo, there is no problems with the name of the folder so `paper.jats` is still used there.

**Comment by arfon** [comment]
Ah great. So there's nothing to do here?

**Comment by xuanxu** [comment]
Right, I think we're good.

**Pull request merged**
