### PR TITLE
Add ROR affiliation links

### LINKED ISSUE #71: Enable annotating ROR identifiers to affiliations
In the same way an ORCID identifier makes an author unambiguous, a ROR identifier can help identify a top-level organization (though sadly not a department). It would be cool to be able annotate ROR identifiers on to affiliations and have them rendered in the manuscript and in the journal metadata

This looks like the spot where ROR IDs could be added into the default latex template:

https://github.com/openjournals/inara/blob/f47cfd4e87d5d1afda9db353966b5102f9c941f2/data/templates/default.latex#L415-L417

cc @mariagould @amandafrench

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #71 

This PR does the following:

- [x] Adds the ability to specify `ror` in each affiliation in a paper's frontmatter
- [x] Adds a ROR logo with a link when `ror` is available in PDF exports
   - [x] `default.tex`
   - [x] `preprint.tex`
- [x] Adds affiliation outputs to `default.crossref` so structured affiliations appear in Crossref metadata (with gracious help from Albert!)
- [x] Adds structured affiliation outputs to JATS export by virtue of it being based on the crossref output 
   

## Demos

Here's what the example PDF looks like now, with a clickable ROR logo that goes to the relevant page:

Screenshot 2024-09-02 at 17 18 19

Here's an example of what the CrossRef XML looks like after running `make ARTICLE=example/paper.md crossref`:
```xml
<contributors>
  <person_name sequence="first" contributor_role="author">
    <given_name>Albert</given_name>
    <surname>Krewinkel</surname>
    <ORCID>https://orcid.org/0000-0002-9455-0796</ORCID>
    <affiliations>
      <institution><institution_name>Open Journals</institution_name></institution>
      <institution><institution_name>Pandoc Development Team</institution_name></institution>
      <institution><institution_name>Technische Universitaet Hamburg</institution_name><institution_id type="ror">https://ror.org/04bs1pb34</institution_id></institution>
    </affiliations>
  </person_name>
   ...
</contributors>
``` 

Here's what the JATS XML looks like:

```xml
...
<aff id="aff-4">
<institution-wrap>
<institution>Technische Universitaet Hamburg</institution>
<institution-id institution-id-type="ROR">04bs1pb34</institution-id>
</institution-wrap>
</aff>
```

It's in the README already, but here are the commands I ran after installing the [hack](https://github.com/source-foundry/Hack) font, `pandoc`, and some other stuff that already was on my computer:

```sh
make ARTICLE=example/paper.md crossref
```

## Notes

1. I converted the official [ror-icon-rgb.svg](https://raw.githubusercontent.com/ror-community/ror-logos/main/ror-icon-rgb.svg) to TikZ code using [svg2tikz](https://github.com/xyz2tex/svg2tikz).
2. I weirdly needed to use `\protect` on both `\href` and the TikZ commands to get them working in the `default.tex` and `preprint.tex` templates
3. I used the [Crossref guide](https://www.crossref.org/documentation/schema-library/markup-guide-metadata-segments/affiliations) to reverse-engineer the way the XML should be
4. I ~am assuming~ incorrectly that the JATS files are created from the output XML since there are no templates related to JATS in the Inara repo. This actually needs to be handled upstream in Pandoc itself - see https://github.com/jgm/pandoc/issues/10138.

## Future Work

A few nice-to-have's (for future PRs):

1. Externalize the code that generates the TikZ picture for ROR into either 1) an external latex file or 2) a package like [`orcidlink`](https://ctan.org/pkg/orcidlink)
2. Add logos int the `default.context`. From what I understand, this is an experiment for Inara to adopt ConTeXt as a typesetting system instead of LaTeX since it has nicer features for PDF export. Since this hasn't been fully adopted by Inara/OJ, I won't make any changes here in this PR but will leave for later.)
3. Crossref/JATS also support Wikidata identifiers and ISNI for organizations. This is especially useful for organizations that don't fall under ROR's scope

### CODE REVIEW

**Comment by cthoyt** [comment]
I'm currently having issues getting `\href{}` to work inside the `\affil` command. It also appears that I can't get the tikz macro working inside `\affil` either, but I've confirmed that it works inside the document section. Note: I'm not very good at latex

**Comment by cthoyt** [comment]
I figured out how to get a lua filter working to reformat the author/affiliation information to get crossref generation working, but I ran into the issue that nested for loops in the pandoc template engine doesn't seem to be possible. They suggest switching to using Lua to construct the information you want, and I'm not ready for that quite yet

**Comment by cthoyt** [comment]
Update: I have figured out how to get the script to build up some arbitrary XML in a string, but for some reason it's not finding its way into the pandoc template

**Comment by cthoyt** [comment]
@tarleb I am a novice in latex and lua, maybe you can very quickly give me a pointer on why the combination of my lua filter and minor changes in `default.context` aren't working properly

**Comment by tarleb** [comment]
Very cool, thanks for this!

The "secret" for `default.crossref` is that the raw strings in the metadata will not be written *as-is*, but will get escaped. To get the raw string, one must wrap the xml with `pandoc.RawInline('html', xml)` in Lua. The CrossRef format basically uses HTML syntax for inline markup, so we use pandoc's HTML writer to produce the output.

If it doesn't work, then we could schedule a short call later this week. Just send me a mail in that case.

**Comment by cthoyt** [comment]
@tarleb I think this is done. It also appears that the JATS seems to be correctly sucking up the crossref metadata.

However, I have run `make test` and am not sure what the protocol for updating the testing data is. I was able to manually check the JATS output is updated and correct, but it's not clear about the other test reference files. There appear to be non-related changes in the newly generated artifacts.

**Comment by cthoyt** [comment]
@arfon your feedback would also be appreciated!

**Comment by arfon** [comment]
Super cool, thanks @cthoyt. If @tarleb is happy, I'm happy 😸 

One cheeky request, once this lands, it would be excellent if you could open a PR for the example JOSS paper too 🙏 https://joss.readthedocs.io/en/latest/example_paper.html

**Comment by amandafrench** [comment]
Hey all, Amanda from ROR here. This is cool! I've added Open Journals to our list of ROR integrators at https://bit.ly/ror-integrations -- take a look and let me know if you'd like changes. cc @cthoyt

**Comment by cthoyt** [comment]
@tarleb did you see this one also?

**Review by tarleb — APPROVED** [review]

**Comment by tarleb** [comment]
We'll need to do a new release before it's fully live. Working on it.

**Comment by tarleb** [comment]
Release v1.1.0 is out. I believe that @xuanxu may have to do some updates before it's used in production.

**Comment by cthoyt** [comment]
thanks @tarleb and everyone for taking a look at this and the nice feedback! looking forward to using this in my upcoming JOSS submission <4

**Comment by arfon** [comment]
Hi folks. I have a feeling that this change might have just broken the production pipeline for JOSS. See this error: https://github.com/openjournals/joss-papers/actions/runs/10718073016/job/29719156977#step:3:808

**Comment by cthoyt** [comment]
could this be because of a disconnect in the way affiliation indexes are written out? It seemed to me like Inara had thrown out the concept of using stringified lists for indexes

**Comment by cthoyt** [comment]
See potential fix in https://github.com/openjournals/inara/pull/77

**Comment by tarleb** [comment]
I've pushed a temporary fix that ignores all errors in the new filter. Now we do a proper fix (and add some appropriate tests).

**Pull request merged**
